"""
Utility functions for fiber photometry form
"""
import logging
import os
import subprocess
import sys
from pathlib import Path

# log configurations
log_file_path = "C:\\Temp\\fiber_photometry_form.log" if os.name == "nt" else "/tmp/fiber_photometry_form.log"
os.makedirs(os.path.dirname(log_file_path), exist_ok=True)
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)-8s [%(filename)s:%(lineno)d] %(message)s",
                    handlers=[logging.FileHandler(log_file_path), logging.StreamHandler(sys.stdout)])
log = logging.getLogger("fiber_photometry_form")
log.info("Fiber Photometry Form Init")


def convert_ui_file_to_py(file_location: str, output_file_name: str) -> str:
    """
    Converts ui file that is generated by Qt Designer to py

    Parameters
    ----------
    file_location: str
        location of the ui file
    output_file_name: str
        the name of the output file

    Returns
    -------
    str
        location of the resulting py file
    """
    if not Path(file_location).exists():
        log.error(f"{file_location} - UI file does not exist, exiting...")
        exit(1)
    sp_cmd = ["pyuic5", f"--output={output_file_name}", file_location]
    try:
        subprocess.run(sp_cmd)
        log.debug(f"{file_location} file converted to .py file named: {output_file_name}")
    except subprocess.SubprocessError:
        raise
    return output_file_name


def test_convert_ui_file_to_py():
    test_file = "fiber_photometry_form.ui"
    ui_to_py_file = convert_ui_file_to_py(test_file, "some_output.py")
    print(f".ui file converted to .py file named: {ui_to_py_file}")
