"""
Utility functions for fiber photometry form
"""
import subprocess
from pathlib import Path

from iblutil.util import get_logger

log = get_logger(name="fiber_photometry_form", file=True)


def convert_ui_file_to_py(file_location: str, output_file_name: str) -> str:
    """
    Converts ui file that is generated by Qt Designer to py

    Parameters
    ----------
    file_location: str
        location of the ui file
    output_file_name: str
        the name of the output file

    Returns
    -------
    str
        location of the resulting py file
    """
    if not Path(file_location).exists():
        log.error(f"{file_location} - UI file does not exist, exiting...")
        exit(1)
    sp_cmd = ["pyuic5", f"--output={output_file_name}", file_location]
    try:
        subprocess.run(sp_cmd)
        log.debug(f"{file_location} file converted to .py file named: {output_file_name}")
    except subprocess.SubprocessError:
        raise
    return output_file_name


def test_convert_ui_file_to_py():
    test_file = "fiber_photometry_form.ui"
    ui_to_py_file = convert_ui_file_to_py(test_file, "some_output.py")
    print(f".ui file converted to .py file named: {ui_to_py_file}")
