cameras:
  body:
      collection: raw_video_data
      sync_label: frame2ttl
      compressed: True
  left:
      collection: raw_video_data
      sync_label: frame2ttl
      compressed: True
  right:
      collection: raw_video_data
      sync_label: frame2ttl
      compressed: True