devices:
  mesoscope:
    mesoscope:
      collection: raw_imaging_data
      sync_label: chrono
procedures:
- Mesoscope recording
projects:
- ibl_neuropixel_brainwide_01
sync:
  nidq:
    acquisition_software: timeline
    collection: raw_sync_data
    extension: npy
tasks:
- ephysChoiceWorld:
    collection: raw_behavior_data
    sync_label: bpod
    extractors: [TrialRegisterRaw, ChoiceWorldTrialsTimeline, TrainingStatus]
- passiveChoiceWorld:
    collection: raw_passive_data
    sync_label: bpod
version: 1.0.0
