devices:
  mesoscope:
    mesoscope:
      collection: raw_imaging_data*
      sync_label: chrono
  cameras:
    belly:
      collection: raw_video_data
      sync_label: frame2ttl
      width: 640
      height: 512
      fps: 30
    left:
      collection: raw_video_data
      sync_label: frame2ttl
    right:
      collection: raw_video_data
      sync_label: frame2ttl
procedures:
- Mesoscope recording
projects:
- ibl_mesoscope_active
sync:
  nidq:
    acquisition_software: timeline
    collection: raw_sync_data
    extension: npy
tasks:
- ephysChoiceWorld:
    collection: raw_behavior_data
    sync_label: bpod
    extractors: [TrialRegisterRaw, ChoiceWorldTrialsTimeline, TrainingStatus]
- passiveChoiceWorld:
    collection: raw_passive_data
    sync_label: bpod
    extractors: [PassiveRegisterRaw, PassiveTaskTimeline]
version: 1.0.0
