---
- name: mbox playbook
  hosts: localhost
  connection: local
  vars_files:
    - vars.yaml
  tasks:
    # OS Tasks
    - name: Ensure hostname is set
      hostname:
        name: "{{ os_host_name }}"

    - name: Ensure required apt packages are present
      apt:
        pkg:
          - awscli
          - git
          - python3-pip
          - python3-venv
          - python3-virtualenv
        update_cache: yes
        state: latest
        autoclean: yes
      become: true


    # Logging Tasks
    - name: Ensure IBL log directory exists
      file:
        path: "{{ ibl_log_dir }}"
        state: directory
        owner: "{{ os_user }}"
        group: "{{ os_group }}"
        mode: 0775

    - name: Ensure log files exist
      file:
        path: "{{ ansible_log_path }}"
        state: touch
        owner: "{{ os_user }}"
        group: "{{ os_group }}"
        mode: 0664
        modification_time: preserve
        access_time: preserve

    # Git Tasks
    - name: Git clone iblalyx repo
      git:
        repo: https://github.com/int-brain-lab/iblalyx.git
        dest: "{{ git_iblalyx_dir }}"
        clone: yes
        update: yes

    # Globus Tasks
    - name: Ensure globus is installed/configured
      shell: |
        virtualenv {{ os_user_home_dir }}/venv
        source {{ os_user_home_dir }}/venv/bin/activate
        pip install globus-cli
        # globus login  # Need a automated way to login to globus

    - import_tasks: crons.yaml